# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-24 10:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bottle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('drink_with', models.CharField(max_length=255, verbose_name='Пить с')),
                ('temperature', models.IntegerField(verbose_name='Пить при')),
                ('ABV', models.IntegerField(verbose_name='ABV')),
                ('OG', models.IntegerField(verbose_name='OG')),
                ('IBU', models.IntegerField(verbose_name='IBU')),
            ],
        ),
        migrations.CreateModel(
            name='BottleProperties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
        ),
        migrations.CreateModel(
            name='BottlePropLevelSpecif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(verbose_name='Уровень')),
            ],
        ),
        migrations.CreateModel(
            name='Wineglasses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
        ),
        migrations.AddField(
            model_name='bottleproplevelspecif',
            name='level_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Level', verbose_name='Уровень'),
        ),
        migrations.AddField(
            model_name='bottleproplevelspecif',
            name='prop_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.BottleProperties', verbose_name='Свойство'),
        ),
        migrations.AddField(
            model_name='bottle',
            name='drink_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Wineglasses', verbose_name='Пить из'),
        ),
    ]
