# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-24 10:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottleproplevelspecif',
            name='bottle',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.Bottle', verbose_name='Бутылка'),
        ),
    ]
