# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-24 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_bottleproplevelspecif_bottle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bottle',
            options={'verbose_name': 'Пиво', 'verbose_name_plural': 'Пиво'},
        ),
        migrations.AlterModelOptions(
            name='bottleproperties',
            options={'verbose_name': 'Свойство', 'verbose_name_plural': 'Свойства'},
        ),
        migrations.AlterModelOptions(
            name='bottleproplevelspecif',
            options={'verbose_name': 'Свойство', 'verbose_name_plural': 'Свойства'},
        ),
        migrations.AlterModelOptions(
            name='level',
            options={'verbose_name': 'Уровень', 'verbose_name_plural': 'Уровни'},
        ),
        migrations.AlterModelOptions(
            name='wineglasses',
            options={'verbose_name': 'Бокал', 'verbose_name_plural': 'Бокалы'},
        ),
        migrations.AddField(
            model_name='bottle',
            name='image_index',
            field=models.ImageField(null=True, upload_to='app/static/images/bottles/', verbose_name='Картинка на главную'),
        ),
        migrations.AddField(
            model_name='bottle',
            name='image_index_dark',
            field=models.ImageField(null=True, upload_to='app/static/images/bottles', verbose_name='Картинка новости (затемнённая)'),
        ),
    ]
