# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-04-24 11:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180424_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottle',
            name='composition',
            field=models.TextField(default='', verbose_name='Состав'),
        ),
        migrations.AddField(
            model_name='bottle',
            name='text',
            field=models.TextField(default='', verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='bottleproplevelspecif',
            name='bottle',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='app.Bottle', verbose_name='Бутылка'),
        ),
        migrations.AlterField(
            model_name='bottleproplevelspecif',
            name='level_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level', to='app.Level', verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='bottleproplevelspecif',
            name='prop_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prop', to='app.BottleProperties', verbose_name='Свойство'),
        ),
    ]
