# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-07 18:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_bottle_volume'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('short_description', models.CharField(max_length=255, verbose_name='Короткое описание')),
                ('text', models.TextField(verbose_name='Текст')),
                ('image', models.ImageField(null=True, upload_to='app/static/images/news/', verbose_name='Картинка')),
            ],
            options={
                'verbose_name_plural': 'Новости и статьи',
                'verbose_name': 'Новость',
            },
        ),
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name_plural': 'Категории статей',
                'verbose_name': 'Категория статей',
            },
        ),
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.NewsCategory'),
        ),
    ]
