# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-13 11:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20180512_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeerGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('image', models.ImageField(upload_to='bottles_groups/', verbose_name='Иконка')),
            ],
            options={
                'verbose_name': 'Тип пива',
                'verbose_name_plural': 'Типы пива',
            },
        ),
        migrations.CreateModel(
            name='BottleTagSpecif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bottle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag', to='app.Bottle', verbose_name='Бутылка')),
            ],
            options={
                'verbose_name': 'Тег для фильтра',
                'verbose_name_plural': 'Теги для фильтра',
            },
        ),
        migrations.CreateModel(
            name='FilterTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тег для фильтра',
                'verbose_name_plural': 'Теги для фильтра',
            },
        ),
        migrations.AlterModelOptions(
            name='bottleproplevelspecif',
            options={'verbose_name': 'Свойство пива', 'verbose_name_plural': 'Свойства пива'},
        ),
        migrations.AlterField(
            model_name='newsbottlespecif',
            name='news_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_item_specif', to='app.News', verbose_name='Новость'),
        ),
        migrations.AddField(
            model_name='bottletagspecif',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filter_tag', to='app.FilterTag', verbose_name='Тег для фильтра'),
        ),
        migrations.AddField(
            model_name='bottle',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.BeerGroup', verbose_name='Тип пива'),
        ),
    ]
