# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-13 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20180513_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='beergroup',
            name='image2',
            field=models.ImageField(null=True, upload_to='bottles_groups/', verbose_name='Иконка (неактивн.)'),
        ),
    ]
