# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-14 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_beergroup_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='beergroup',
            name='url',
            field=models.CharField(default='', max_length=255, verbose_name='Url'),
        ),
    ]
