# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-14 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_beergroup_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='filtertag',
            name='url',
            field=models.CharField(default='', max_length=255, verbose_name='url'),
        ),
    ]
