# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-28 13:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_filtertag_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPhotoSpecif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='News/', verbose_name='Фото')),
                ('news_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='app.News', verbose_name='Фото в галлерею')),
            ],
        ),
    ]
