# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-29 14:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_newsphotospecif'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsphotospecif',
            options={'verbose_name': 'Фото в галлерею', 'verbose_name_plural': 'Фото в галлерею'},
        ),
        migrations.AddField(
            model_name='bottle',
            name='sub_name',
            field=models.CharField(default='', max_length=255, verbose_name='Транслит'),
        ),
        migrations.AlterField(
            model_name='newsphotospecif',
            name='news_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_photos', to='app.News', verbose_name='Фото в галлерею'),
        ),
    ]
