# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-29 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20180529_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottletagspecif',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.BeerGroup', verbose_name='Тип пива'),
        ),
    ]
