# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-29 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_bottletagspecif_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottletagspecif',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beer_type', to='app.BeerGroup', verbose_name='Тип пива'),
        ),
    ]
