# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-29 15:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20180529_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bottletagspecif',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat', to='app.BeerGroup', verbose_name='Тип пива'),
        ),
    ]
