# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-03 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20180529_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='beergroup',
            name='text',
            field=models.TextField(default='', verbose_name='Текст'),
        ),
    ]
