# Generated by Django 2.0.7 on 2018-07-04 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_beergroup_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='wineglasses',
            name='image',
            field=models.ImageField(null=True, upload_to='bottles_groups/', verbose_name='Фотография'),
        ),
        migrations.AddField(
            model_name='wineglasses',
            name='text',
            field=models.TextField(default='', verbose_name='Короткое описание'),
        ),
        migrations.AddField(
            model_name='wineglasses',
            name='url',
            field=models.CharField(default='', max_length=255, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='drink_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Wineglasses', verbose_name='Пить из'),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app.BeerGroup', verbose_name='Тип пива'),
        ),
        migrations.AlterField(
            model_name='bottleproplevelspecif',
            name='bottle',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='app.Bottle', verbose_name='Бутылка'),
        ),
        migrations.AlterField(
            model_name='bottleproplevelspecif',
            name='level_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='level', to='app.Level', verbose_name='Уровень'),
        ),
        migrations.AlterField(
            model_name='bottleproplevelspecif',
            name='prop_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prop', to='app.BottleProperties', verbose_name='Свойство'),
        ),
        migrations.AlterField(
            model_name='bottletagspecif',
            name='bottle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tag', to='app.Bottle', verbose_name='Бутылка'),
        ),
        migrations.AlterField(
            model_name='bottletagspecif',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='filter_tag', to='app.FilterTag', verbose_name='Тег для фильтра'),
        ),
        migrations.AlterField(
            model_name='filtertag',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cat', to='app.BeerGroup', verbose_name='Тип пива'),
        ),
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category', to='app.NewsCategory', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='newsbottlespecif',
            name='bottle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bottle', to='app.Bottle', verbose_name='Бутылка'),
        ),
        migrations.AlterField(
            model_name='newsbottlespecif',
            name='news_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='news_item_specif', to='app.News', verbose_name='Новость'),
        ),
        migrations.AlterField(
            model_name='newsphotospecif',
            name='news_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gallery_photos', to='app.News', verbose_name='Фото в галлерею'),
        ),
    ]
