# Generated by Django 2.0.7 on 2018-07-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20180704_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wineglasses',
            name='url',
        ),
        migrations.AlterField(
            model_name='wineglasses',
            name='text',
            field=models.TextField(default='', verbose_name='Краткое описание'),
        ),
    ]
