# Generated by Django 2.0.7 on 2018-07-10 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20180709_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottle',
            name='image_big',
            field=models.ImageField(null=True, upload_to='app/static/images/bottles/', verbose_name='Фото большое'),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='image_index',
            field=models.ImageField(null=True, upload_to='app/static/images/bottles/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='bottle',
            name='image_index_dark',
            field=models.ImageField(null=True, upload_to='app/static/images/bottles', verbose_name='Фото (затемнённое)'),
        ),
    ]
