# Generated by Django 2.0.7 on 2018-07-10 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20180710_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='description',
            field=models.CharField(default='', max_length=255, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='news',
            name='keywords',
            field=models.CharField(default='', max_length=255, verbose_name='Keywords'),
        ),
        migrations.AddField(
            model_name='news',
            name='title',
            field=models.CharField(default='', max_length=255, verbose_name='Тайтл'),
        ),
    ]
