# Generated by Django 2.0.7 on 2018-07-10 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20180710_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='description',
        ),
        migrations.RemoveField(
            model_name='news',
            name='keywords',
        ),
        migrations.RemoveField(
            model_name='news',
            name='title',
        ),
    ]
